http: 
    routers: 
        api:
            rule: PathPrefix(`/api`)
            service: api
        serving:
            rule: PathPrefix(`/serving`)
            service: serving
        jupyter: 
            rule: PathPrefix(`/jupyter`)
            service: jupyter
        workbench: 
            rule: PathPrefix(`/`)
            service: workbench
    services: 
        jupyter: 
            loadBalancer: 
                servers: 
                  - url: "http://127.0.0.1:8888"
        api: 
            loadBalancer: 
                servers: 
                  - url: "http://127.0.0.1:3002"
        serving: 
            loadBalancer: 
                servers: 
                  - url: "http://127.0.0.1:8000"
        workbench: 
            loadBalancer: 
                servers: 
                  - url: "http://127.0.0.1:3001"
  